Feature/s3 bucket per vpc
trocafone/terraform-aws-vpc pull request #3
Opened 2018-05-29 17:14 UTC by fwelschen

2018-05-29 17:33 UTC, fwelschen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Terraform / Kops :: K8s Cluster en Staging](https://trello.com/c/YlyoG7mP/449-terraform-kops-k8s-cluster-en-staging)

2018-05-29 20:16 UTC, idontdomath requested changes
Maybe we should find a more specific name of the variable in order to explain why we are using this, or why we are creating it.

2018-05-29 20:16 UTC, idontdomath commented on outputs.tf
> +  #count = "${var.enable_s3_bucket ? 1 : 0}"
remove.

2018-05-29 20:16 UTC, idontdomath commented on main.tf
> +# Bucket S3 ## We use it for k8s
maybe instead of commenting this as it's specifically for k8s we should mention that it's used for metadata on implementations.

2018-05-30 19:20 UTC, idontdomath approved these changes
🚢 it!

2018-05-30 19:29 UTC, merged